version: '3'

tasks:
  default:
    deps:
      - lint
      - test
  lint:
    deps:
      - vuln
      - vet
  test:
    cmds:
      - go tool gotestsum --format pkgname --format-icons hivis -- -cover -race ./...
  vuln:
    cmds:
      - go tool govulncheck ./...
  vet:
    cmds:
      - go vet ./...
  generate:
    # deps:
    #   - clean-generated
    cmds:
      - go generate ./...
  clean-generated:
    cmds:
      - find . -name "*_generated.go" -type f -delete
  tidy:
    cmds:
      - go mod tidy -v
