// Code generated by "dataclass -type StructField -field Name string|Kind reflect.Kind|Tag *Tag -output structfield_dataclass_generated.go"; DO NOT EDIT.

package internal

import "reflect"

type StructField interface {
	Name() string
	Kind() reflect.Kind
	Tag() *Tag
}
type structField struct {
	name string
	kind reflect.Kind
	tag  *Tag
}

func (s *structField) Name() string       { return s.name }
func (s *structField) Kind() reflect.Kind { return s.kind }
func (s *structField) Tag() *Tag          { return s.tag }
func NewStructField(
	name string,
	kind reflect.Kind,
	tag *Tag,
) StructField {
	return &structField{
		name: name,
		kind: kind,
		tag:  tag,
	}
}
